"""Helpers for reading generated stellar-bubble simulation outputs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass(frozen=True)
class SimulationOutput:
    """A generated modulation grid."""

    radius_cm: np.ndarray
    energy_erg: np.ndarray
    modulation: np.ndarray


def parse_output_filename(filename: str) -> tuple[str, float, float]:
    """Parse names such as ``G5V_B1.0_V30.0`` into model parameters."""

    stem = Path(filename).name
    parts = stem.split("_")
    if len(parts) != 3 or not parts[1].startswith("B") or not parts[2].startswith("V"):
        raise ValueError(f"Unrecognised simulation output filename: {filename}")

    spectral_class = parts[0]
    magnetic_field = float(parts[1][1:])
    stellar_velocity = float(parts[2][1:])
    return spectral_class, magnetic_field, stellar_velocity


def read_simulation_output(path: str | Path, energy_bins: int = 500) -> SimulationOutput:
    """Read a whitespace-delimited output file generated by the model scripts."""

    data = np.loadtxt(path, unpack=True)
    if data.shape[0] != 3:
        raise ValueError("Simulation output must contain radius, energy, and modulation columns")

    radius, energy, modulation = data
    if radius.size % energy_bins != 0:
        raise ValueError(
            f"Expected row count to be divisible by {energy_bins}, got {radius.size}"
        )

    radius_bins = radius.size // energy_bins
    shape = (energy_bins, radius_bins)
    return SimulationOutput(
        radius_cm=radius.reshape(shape),
        energy_erg=energy.reshape(shape),
        modulation=modulation.reshape(shape),
    )
